channels:
- conda-forge
dependencies:
- python=3.9.7
- pip<=24.0
- pip:
  - mlflow==2.9.2
  - cloudpickle==2.2.1
  - importlib-metadata==6.0.0
  - numpy==1.24.3
  - packaging==23.0
  - psutil==5.9.4
  - pyyaml==6.0
  - scikit-learn==1.2.0
  - scipy==1.10.0
name: mlflow-env
